#!/usr/bin/env bash

# Get nicely formatted version string using 'git describe' command.
# This will error if there are no tags, so we redirect stderr.
version=$(git describe 2> /dev/null)

if [ ! -z $version ];
then
    # Switch first - character with a + to match versioneer formatting
    # in the main MetaWards repository.
    echo $version | sed 's/-/+/' > version.txt
fi
